"use client";

import { useEffect, useState } from "react";
import { Check, CheckSquare2, Clock3, Loader2, Plus, Trash2 } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { EmptyState } from "@/components/EmptyState";
import { api } from "@/lib/api";

const filters = ["all", "todo", "in_progress", "completed"];
export default function TasksPage() {
  const [tasks, setTasks] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [filter, setFilter] = useState("all"); const [show, setShow] = useState(false);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [priority, setPriority] = useState("medium"); const [dueDate, setDueDate] = useState(""); const [minutes, setMinutes] = useState(30); const [saving, setSaving] = useState(false);
  const load = () => { setLoading(true); api.getTasks(filter === "all" ? undefined : { status: filter }).then(setTasks).finally(() => setLoading(false)); }; useEffect(load, [filter]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await api.createTask({ title: title.trim(), description: description.trim() || undefined, priority, due_date: dueDate ? new Date(dueDate).toISOString() : undefined, estimated_minutes: minutes }); setTitle(""); setDescription(""); setDueDate(""); setShow(false); load(); } finally { setSaving(false); } };
  const toggle = async (task: any) => { await api.updateTask(task.id, { status: task.status === "completed" ? "todo" : "completed" }); load(); };
  const remove = async (id: string) => { await api.deleteTask(id); load(); };
  return <AppShell title="Tasks" description="A short queue of clear next actions."><div className="mx-auto max-w-5xl space-y-5">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-[#9A6500]">Action list</p><h2 className="mt-1 text-[19px] font-semibold tracking-tight text-[#1B1B2F]">Keep work moving</h2><p className="mt-1 text-[11px] text-[#6B6B80]">Small, concrete steps beat a crowded plan.</p></div><button onClick={() => setShow(true)} className="btn-primary w-fit"><Plus className="h-4 w-4" />Add task</button></div>
    <div className="flex max-w-full gap-1 overflow-x-auto rounded-xl bg-[#EEEDF5] p-1 sm:w-fit">{filters.map(item => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-3 py-1.5 text-[10px] font-semibold capitalize transition ${filter === item ? "bg-white text-[#1B1B2F]" : "text-[#6B6B80] hover:text-[#1B1B2F]"}`}>{item.replace("_", " ")}</button>)}</div>
    {loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#9291A5]" /></div> : tasks.length === 0 ? <EmptyState icon={CheckSquare2} title={filter === "completed" ? "Nothing completed yet" : "Your list is clear"} description="Add one concrete next action. You can always organize it later." action={filter !== "completed" ? <button onClick={() => setShow(true)} className="btn-primary">Add a task</button> : undefined} /> : <div className="surface-flat divide-y divide-[#F0F0F7] overflow-hidden">{tasks.map(task => <article key={task.id} className="group flex items-start gap-4 px-4 py-4 transition hover:bg-[#FAFAFE] sm:px-5"><button onClick={() => toggle(task)} className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full border transition ${task.status === "completed" ? "border-[#6C5CE7] bg-[#6C5CE7] text-white" : "border-[#C7C5DC] hover:border-[#6C5CE7]"}`} aria-label={`Mark ${task.title} ${task.status === "completed" ? "open" : "complete"}`}>{task.status === "completed" && <Check className="check-draw h-3 w-3" />}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className={`text-[13px] font-medium ${task.status === "completed" ? "text-[#9291A5] line-through" : "text-[#1B1B2F]"}`}>{task.title}</h3><span className={`rounded-full px-2 py-0.5 text-[8px] font-semibold uppercase tracking-wide ${task.priority === "urgent" ? "bg-[#FFEAE8] text-[#C4392E]" : task.priority === "high" ? "bg-[#FFF4E0] text-[#9A6500]" : task.priority === "medium" ? "bg-[#EEEDFE] text-[#4C3FBF]" : "bg-[#F0F0F7] text-[#6B6B80]"}`}>{task.priority}</span></div>{task.description && <p className="mt-1 text-[11px] leading-5 text-[#6B6B80]">{task.description}</p>}<div className="mono mt-2 flex flex-wrap gap-3 text-[9px] text-[#9291A5]"><span className="flex items-center gap-1"><Clock3 className="h-3 w-3" />{task.estimated_minutes} min</span>{task.due_date && <span>Due {new Date(task.due_date).toLocaleDateString()}</span>}</div></div><button onClick={() => remove(task.id)} className="rounded-lg p-2 text-[#C7C5DC] opacity-100 transition hover:bg-[#FFEAE8] hover:text-[#C4392E] sm:opacity-0 sm:group-hover:opacity-100" aria-label={`Delete ${task.title}`}><Trash2 className="h-4 w-4" /></button></article>)}</div>}
    {show && <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/35 p-4 backdrop-blur-sm" onMouseDown={event => event.currentTarget === event.target && setShow(false)}><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><p className="eyebrow">New action</p><h3 className="mt-1 text-xl font-bold text-slate-950">Add a task</h3><form onSubmit={create} className="mt-6 space-y-4"><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Task</label><input autoFocus className="field" value={title} onChange={e => setTitle(e.target.value)} placeholder="What needs to happen?" required /></div><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Notes</label><textarea className="field min-h-20 resize-none" value={description} onChange={e => setDescription(e.target.value)} placeholder="Optional context" /></div><div className="grid gap-3 sm:grid-cols-3"><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Priority</label><select className="field" value={priority} onChange={e => setPriority(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></div><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Minutes</label><input className="field" type="number" min={1} max={1440} value={minutes} onChange={e => setMinutes(Number(e.target.value))} /></div><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Due date</label><input className="field" type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} /></div></div><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={() => setShow(false)} className="btn-secondary">Cancel</button><button className="btn-primary" disabled={saving || !title.trim()}>{saving ? "Adding…" : "Add task"}</button></div></form></div></div>}
  </div></AppShell>;
}
