"use client";

import { useEffect, useState } from "react";
import { Bell, Brain, Check, KeyRound, Loader2, Plus, Trash2, UserRound } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";

type Tab = "ai" | "notifications" | "memory" | "profile";
const tabs = [{ id: "ai", label: "AI models", icon: KeyRound }, { id: "notifications", label: "Notifications", icon: Bell }, { id: "memory", label: "Memory", icon: Brain }, { id: "profile", label: "Profile", icon: UserRound }] as const;

export default function SettingsPage() {
  const { user, updateUser } = useAuth(); const [tab, setTab] = useState<Tab>("ai"); const [loading, setLoading] = useState(true); const [status, setStatus] = useState("");
  const [ai, setAi] = useState<any>({ use_platform_default: true, provider: "groq", api_key: "", base_url: "", default_model: "", model_mode: "balanced", allow_fallback: false, masked_api_key: null });
  const [prefs, setPrefs] = useState<any>({}); const [memories, setMemories] = useState<any[]>([]); const [fact, setFact] = useState(""); const [category, setCategory] = useState("preference"); const [name, setName] = useState(user?.full_name || "");
  useEffect(() => { const requestedTab = new URLSearchParams(window.location.search).get("tab"); if (["ai", "notifications", "memory", "profile"].includes(requestedTab || "")) setTab(requestedTab as Tab); Promise.all([api.getAISettings(), api.getNotificationPreferences(), api.getMemories()]).then(([aiData, prefData, memoryData]) => { setAi({ ...aiData, api_key: "" }); setPrefs(prefData); setMemories(memoryData); }).finally(() => setLoading(false)); }, []);
  useEffect(() => { setName(user?.full_name || ""); }, [user]);
  const saved = (message: string) => { setStatus(message); setTimeout(() => setStatus(""), 2500); };
  const saveAi = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); try { const data = await api.updateAISettings({ use_platform_default: ai.use_platform_default, provider: ai.provider, api_key: ai.api_key || undefined, base_url: ai.base_url || undefined, default_model: ai.default_model || undefined, model_mode: ai.model_mode, allow_fallback: ai.allow_fallback }); setAi({ ...data, api_key: "" }); saved("AI settings saved"); } finally { setLoading(false); } };
  const savePrefs = async () => { setLoading(true); try { setPrefs(await api.updateNotificationPreferences(prefs)); saved("Notification preferences saved"); } finally { setLoading(false); } };
  const addMemory = async (event: React.FormEvent) => { event.preventDefault(); if (!fact.trim()) return; const item = await api.createMemory({ fact: fact.trim(), category, source: "manual" }); setMemories([item, ...memories]); setFact(""); saved("Memory saved"); };
  const removeMemory = async (id: string) => { await api.deleteMemory(id); setMemories(memories.filter(item => item.id !== id)); };
  const saveProfile = async (event: React.FormEvent) => { event.preventDefault(); const updated = await api.updateProfile({ full_name: name.trim() || null }); updateUser(updated); saved("Profile updated"); };

  return <AppShell title="Settings" description="Keep control of your workspace, models, and private context.">
    <div className="grid gap-6 lg:grid-cols-[210px_1fr]">
      <aside className="h-fit rounded-[14px] border border-[#E4E3F5] bg-white p-2">{tabs.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[11px] font-medium transition ${tab === item.id ? "bg-[#EEEDFE] text-[#4C3FBF]" : "text-[#6B6B80] hover:bg-[#F7F7FC]"}`}><Icon className="h-4 w-4" />{item.label}</button>; })}</aside>
      <section className="surface min-h-[520px] p-6 md:p-8">{status && <div className="mb-6 flex items-center gap-2 rounded-xl bg-[#E3FBF7] px-4 py-3 text-xs font-semibold text-[#00846F]"><Check className="h-4 w-4" />{status}</div>}
        {tab === "ai" && <form onSubmit={saveAi} className="max-w-2xl space-y-7"><div><p className="eyebrow">Assistant engine</p><h2 className="mt-1 text-xl font-bold text-slate-950">AI model preferences</h2><p className="mt-2 text-xs leading-5 text-slate-500">Use the platform model or bring your own encrypted provider key.</p></div>
          <div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setAi({ ...ai, use_platform_default: true })} className={`rounded-[14px] border p-4 text-left transition ${ai.use_platform_default ? "border-[#6C5CE7] bg-[#EEEDFE] ring-4 ring-[#6C5CE7]/10" : "border-[#E4E3F5]"}`}><p className="text-sm font-semibold text-[#1B1B2F]">Platform default</p><p className="mt-1 text-xs leading-5 text-[#6B6B80]">Fastest setup with the server-configured model.</p></button><button type="button" onClick={() => setAi({ ...ai, use_platform_default: false })} className={`rounded-[14px] border p-4 text-left transition ${!ai.use_platform_default ? "border-[#6C5CE7] bg-[#EEEDFE] ring-4 ring-[#6C5CE7]/10" : "border-[#E4E3F5]"}`}><p className="text-sm font-semibold text-[#1B1B2F]">Bring your own key</p><p className="mt-1 text-xs leading-5 text-[#6B6B80]">Private provider credentials encrypted at rest.</p></button></div>
          <div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Provider</label><select className="field" disabled={ai.use_platform_default} value={ai.provider} onChange={e => setAi({ ...ai, provider: e.target.value })}><option value="groq">Groq</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Google Gemini</option><option value="ollama">Ollama</option><option value="custom">Custom endpoint</option></select></div><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Response mode</label><select className="field" value={ai.model_mode} onChange={e => setAi({ ...ai, model_mode: e.target.value })}><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="quality">Highest quality</option></select></div></div>
          {!ai.use_platform_default && <div className="space-y-4"><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">API key {ai.masked_api_key && <span className="font-normal text-slate-400">· saved {ai.masked_api_key}</span>}</label><input className="field" type="password" value={ai.api_key} onChange={e => setAi({ ...ai, api_key: e.target.value })} placeholder={ai.masked_api_key ? "Leave blank to keep saved key" : "Paste your API key"} /></div>{["ollama", "custom"].includes(ai.provider) && <div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Base URL</label><input className="field" type="url" value={ai.base_url || ""} onChange={e => setAi({ ...ai, base_url: e.target.value })} placeholder="http://localhost:11434" /></div>}</div>}
          <button className="btn-primary" disabled={loading}>{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Save AI settings"}</button>
        </form>}

        {tab === "notifications" && <div className="max-w-2xl"><div><p className="eyebrow">Attention controls</p><h2 className="mt-1 text-xl font-bold text-slate-950">Notification preferences</h2><p className="mt-2 text-xs leading-5 text-slate-500">Keep high-signal alerts and turn down everything else.</p></div><div className="mt-7 divide-y divide-slate-100">{[{ key: "email_urgent", label: "Urgent email", note: "Critical deadlines and blockers" }, { key: "email_action_needed", label: "Email needs action", note: "Direct requests and pending decisions" }, { key: "cal_reminders", label: "Meeting reminders", note: "Upcoming calendar events" }, { key: "cal_conflicts", label: "Calendar conflicts", note: "Overlapping meetings" }, { key: "task_due_today", label: "Tasks due today", note: "Same-day task deadlines" }, { key: "task_overdue", label: "Overdue tasks", note: "Tasks that slipped past their due date" }, { key: "github_reviews", label: "GitHub reviews", note: "Pull requests waiting for you" }].map(item => <label key={item.key} className="flex cursor-pointer items-center justify-between gap-4 py-4"><div><p className="text-sm font-medium text-slate-800">{item.label}</p><p className="mt-0.5 text-xs text-slate-400">{item.note}</p></div><input type="checkbox" checked={!!prefs[item.key]} onChange={e => setPrefs({ ...prefs, [item.key]: e.target.checked })} className="h-4 w-4 rounded border-slate-300 text-[#6C5CE7] focus:ring-[#6C5CE7]" /></label>)}</div><button onClick={savePrefs} className="btn-primary mt-6" disabled={loading}>Save preferences</button></div>}

        {tab === "memory" && <div><div><p className="eyebrow">Private context</p><h2 className="mt-1 text-xl font-bold text-slate-950">Long-term memory</h2><p className="mt-2 text-xs leading-5 text-slate-500">Facts saved here are isolated to your account and used to personalize recommendations.</p></div><form onSubmit={addMemory} className="mt-6 flex flex-col gap-2 sm:flex-row"><select value={category} onChange={e => setCategory(e.target.value)} className="field sm:w-40"><option value="preference">Preference</option><option value="project">Project</option><option value="contact">Contact</option><option value="decision">Decision</option><option value="routine">Routine</option></select><input className="field flex-1" value={fact} onChange={e => setFact(e.target.value)} placeholder="Add a fact worth remembering…" /><button className="btn-primary" disabled={!fact.trim()}><Plus className="h-4 w-4" />Save</button></form><div className="mt-6 divide-y divide-slate-100 rounded-2xl border border-slate-200">{memories.map(item => <div key={item.id} className="flex items-start gap-3 p-4"><span className="mt-0.5 rounded-full bg-slate-100 px-2 py-1 text-[9px] font-semibold uppercase tracking-wide text-slate-500">{item.category}</span><p className="min-w-0 flex-1 text-sm leading-6 text-slate-700">{item.fact}</p><button onClick={() => removeMemory(item.id)} className="rounded-lg p-2 text-slate-300 hover:bg-red-50 hover:text-red-600" aria-label="Delete memory"><Trash2 className="h-4 w-4" /></button></div>)}{memories.length === 0 && <p className="p-8 text-center text-xs text-slate-400">No saved memories yet.</p>}</div></div>}

        {tab === "profile" && <form onSubmit={saveProfile} className="max-w-xl"><div><p className="eyebrow">Your account</p><h2 className="mt-1 text-xl font-bold text-slate-950">Profile</h2><p className="mt-2 text-xs leading-5 text-slate-500">Simple account details used across your workspace.</p></div><div className="mt-7 space-y-4"><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Full name</label><input className="field" value={name} onChange={e => setName(e.target.value)} placeholder="Your name" /></div><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Email address</label><input className="field bg-slate-50 text-slate-500" value={user?.email || ""} disabled /></div></div><button className="btn-primary mt-6">Save profile</button></form>}
      </section>
    </div>
  </AppShell>;
}
