"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertCircle, Check, Clipboard, Inbox, Loader2, Mail, Plus, RefreshCw, Sparkles, X } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { EmptyState } from "@/components/EmptyState";
import { api } from "@/lib/api";

type Category = "urgent" | "action_needed" | "fyi" | "ignore";
type EmailItem = { id: string; sender: string; subject: string; snippet: string; category: Category; reason: string; suggested_action?: string | null; date: string };
const labels: Record<Category, string> = { urgent: "Urgent", action_needed: "Needs reply", fyi: "FYI", ignore: "Low priority" };
const avatarTints = ["bg-[#EEEDFE] text-[#4C3FBF]", "bg-[#E3FBF7] text-[#00846F]", "bg-[#FFF4E0] text-[#9A6500]", "bg-[#FFEAE8] text-[#C4392E]"];

export default function InboxPage() {
  const [emails, setEmails] = useState<EmailItem[]>([]); const [connected, setConnected] = useState(false); const [account, setAccount] = useState<string | null>(null); const [syncError, setSyncError] = useState(""); const [filter, setFilter] = useState<Category | "all">("all"); const [loading, setLoading] = useState(true);
  const [draftFor, setDraftFor] = useState<EmailItem | null>(null); const [draftSubject, setDraftSubject] = useState(""); const [draftBody, setDraftBody] = useState(""); const [drafting, setDrafting] = useState(false); const [notice, setNotice] = useState("");
  const load = async () => { setLoading(true); setSyncError(""); try { const data = await api.getInbox(); setEmails(data.emails || []); setConnected(!!data.is_connected); setAccount(data.account_email || null); setSyncError(data.sync_error || ""); } catch (error: any) { setSyncError(error.message || "Gmail could not be synchronized."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => filter === "all" ? emails : emails.filter(item => item.category === filter), [emails, filter]);
  const createTask = async (item: EmailItem) => { await api.createTask({ title: item.suggested_action || `Follow up: ${item.subject}`, priority: item.category === "urgent" ? "urgent" : "high", estimated_minutes: 20, source_type: "gmail", source_id: item.id }); setNotice("Follow-up task created."); setTimeout(() => setNotice(""), 2500); };
  const openDraft = async (item: EmailItem) => { setDraftFor(item); setDraftSubject(""); setDraftBody(""); setDrafting(true); try { const result = await api.draftEmailReply({ email_id: item.id, subject: item.subject, snippet: item.snippet }); setDraftSubject(result.draft_subject); setDraftBody(result.draft_body); } finally { setDrafting(false); } };
  const copyDraft = async () => { await navigator.clipboard.writeText(`${draftSubject}\n\n${draftBody}`); setNotice("Draft copied."); setDraftFor(null); setTimeout(() => setNotice(""), 2500); };
  const initials = (sender: string) => sender.replace(/<.*>/, "").trim().split(/\s+/).slice(0, 2).map(part => part[0]).join("").toUpperCase() || "M";

  return <AppShell title="Inbox" description="A quiet queue for messages that need you.">
    <div className="mx-auto max-w-5xl space-y-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-[#C4392E]">Communication</p><h2 className="mt-1 text-[19px] font-semibold tracking-tight text-[#1B1B2F]">Inbox</h2><p className="mt-1 text-[11px] text-[#6B6B80]">{connected ? account : "Connect Gmail to bring the important messages here."}</p></div><div className="flex gap-2">{!connected && <Link href="/integrations" className="btn-primary">Connect Gmail</Link>}<button onClick={load} disabled={loading || !connected} className="btn-secondary"><RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />Refresh</button></div></div>
      {notice && <div className="flex items-center gap-2 rounded-xl bg-[#E3FBF7] px-4 py-3 text-[11px] font-medium text-[#00846F]"><Check className="h-3.5 w-3.5" />{notice}</div>}
      {connected && emails.length > 0 && <div className="flex max-w-full gap-1 overflow-x-auto rounded-xl bg-[#EEEDF5] p-1 sm:w-fit"><button onClick={() => setFilter("all")} className={`rounded-lg px-3 py-1.5 text-[10px] font-semibold ${filter === "all" ? "bg-white text-[#1B1B2F]" : "text-[#6B6B80]"}`}>All · {emails.length}</button>{(["urgent", "action_needed", "fyi"] as Category[]).map(category => <button key={category} onClick={() => setFilter(category)} className={`whitespace-nowrap rounded-lg px-3 py-1.5 text-[10px] font-semibold ${filter === category ? "bg-white text-[#1B1B2F]" : "text-[#6B6B80]"}`}>{labels[category]} · {emails.filter(item => item.category === category).length}</button>)}</div>}

      {loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#9291A5]" /></div> : syncError ? <section className="surface-flat flex items-start gap-4 p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#FFF4E0] text-[#9A6500]"><AlertCircle className="h-5 w-5" /></span><div><h3 className="text-sm font-semibold text-[#1B1B2F]">Gmail needs attention</h3><p className="mt-1 max-w-2xl text-[11px] leading-5 text-[#6B6B80]">{syncError}</p><Link href="/integrations" className="mt-4 inline-flex text-[11px] font-semibold text-[#C4392E]">Reconnect Gmail →</Link></div></section> : !connected ? <EmptyState icon={Inbox} title="Your inbox stays private until you connect it" description="Authorize Gmail when live inbox context is useful. No sample messages are shown." action={<Link href="/integrations" className="btn-primary">Review integrations</Link>} /> : emails.length === 0 ? <EmptyState icon={Inbox} title="Inbox is clear" description="Gmail synchronized successfully and returned no recent messages." /> : <section className="surface-flat overflow-hidden"><div className="divide-y divide-[#F0F0F7]">{filtered.map((item, index) => { const attention = item.category === "urgent" || item.category === "action_needed"; return <article key={item.id} className={`group relative grid grid-cols-[40px_1fr_auto] gap-3 px-4 py-4 transition hover:bg-[#FAFAFE] sm:px-5 ${attention ? "border-l-[3px] border-l-[#FF6B5E]" : "border-l-[3px] border-l-transparent"}`}><span className={`grid h-9 w-9 place-items-center rounded-full text-[10px] font-bold ${avatarTints[index % avatarTints.length]}`}>{initials(item.sender)}</span><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-[11px] font-semibold text-[#1B1B2F]">{item.sender}</p>{attention && <span className="rounded-full bg-[#FFEAE8] px-2 py-0.5 text-[8px] font-semibold uppercase tracking-wide text-[#C4392E]">{labels[item.category]}</span>}</div><h3 className="mt-1 truncate text-[13px] font-semibold text-[#1B1B2F]">{item.subject}</h3><p className="mt-1 line-clamp-1 text-[11px] leading-5 text-[#6B6B80]">{item.snippet}</p><div className="mt-3 flex gap-2 opacity-100 transition sm:opacity-0 sm:group-hover:opacity-100"><button onClick={() => createTask(item)} className="inline-flex items-center gap-1 rounded-lg border border-[#E4E3F5] bg-white px-2.5 py-1.5 text-[9px] font-semibold text-[#6B6B80] hover:text-[#9A6500]"><Plus className="h-3 w-3" />Task</button><button onClick={() => openDraft(item)} className="inline-flex items-center gap-1 rounded-lg bg-[#FFEAE8] px-2.5 py-1.5 text-[9px] font-semibold text-[#C4392E]"><Sparkles className="h-3 w-3" />Draft reply</button></div></div><time className="mono whitespace-nowrap text-[9px] text-[#9291A5]">{item.date}</time></article>; })}</div></section>}
    </div>

    {draftFor && <div className="fixed inset-0 z-[70] grid place-items-center bg-[#1B1B2F]/35 p-4 backdrop-blur-sm"><div className="w-full max-w-xl rounded-[18px] border border-[#E4E3F5] bg-white p-6 shadow-2xl"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#FFEAE8] text-[#C4392E]"><Mail className="h-5 w-5" /></span><div className="flex-1"><h2 className="text-base font-semibold text-[#1B1B2F]">Reply draft</h2><p className="mt-1 text-[11px] text-[#6B6B80]">Review and edit before copying.</p></div><button onClick={() => setDraftFor(null)} className="rounded-lg p-1.5 text-[#9291A5] hover:bg-[#F0F0F7]" aria-label="Close draft"><X className="h-4 w-4" /></button></div>{drafting ? <div className="grid min-h-56 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#6C5CE7]" /></div> : <div className="mt-5 space-y-4"><div><label className="mb-1.5 block text-[11px] font-semibold">Subject</label><input className="field" value={draftSubject} onChange={event => setDraftSubject(event.target.value)} /></div><div><label className="mb-1.5 block text-[11px] font-semibold">Message</label><textarea rows={8} className="field resize-none" value={draftBody} onChange={event => setDraftBody(event.target.value)} /></div></div>}<div className="mt-6 flex justify-end gap-2"><button onClick={() => setDraftFor(null)} className="btn-secondary">Close</button><button onClick={copyDraft} disabled={drafting || !draftBody.trim()} className="btn-primary"><Clipboard className="h-4 w-4" />Copy draft</button></div></div></div>}
  </AppShell>;
}
