"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckSquare2, Loader2, Mail, Sparkles } from "lucide-react";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";

const goals = [{ id: "priorities", label: "Choose the right next task", icon: CheckSquare2 }, { id: "inbox", label: "Reduce inbox noise", icon: Mail }, { id: "schedule", label: "Prepare for meetings", icon: CalendarDays }];
const tools = [{ id: "gmail", label: "Gmail", note: "Connect securely after setup", icon: Mail }, { id: "google_calendar", label: "Google Calendar", note: "Connect securely after setup", icon: CalendarDays }];

export default function OnboardingPage() {
  const router = useRouter(); const { updateUser } = useAuth(); const [step, setStep] = useState(1); const [selectedGoals, setSelectedGoals] = useState<string[]>(["priorities"]); const [selectedTools, setSelectedTools] = useState<string[]>(["gmail", "google_calendar"]); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const toggle = (value: string, list: string[], setter: (items: string[]) => void) => setter(list.includes(value) ? list.filter(item => item !== value) : [...list, value]);
  const finish = async () => { setSaving(true); setError(""); try { const updated = await api.completeOnboarding({ selected_integrations: selectedTools, productivity_goals: selectedGoals }); updateUser(updated); router.push("/integrations"); } catch (err: any) { setError(err.message || "Setup could not be completed."); } finally { setSaving(false); } };
  return <main className="min-h-screen bg-[#f5f7fb] px-4 py-6 sm:px-7"><div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-4xl flex-col rounded-[28px] border border-slate-200 bg-white shadow-[0_20px_70px_rgba(15,23,42,.07)]">
    <header className="flex items-center justify-between border-b border-slate-100 px-6 py-5 sm:px-8"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600 text-white"><Sparkles className="h-4 w-4" /></div><div><p className="text-sm font-bold text-slate-950">Northstar</p><p className="text-[10px] text-slate-400">Workspace setup</p></div></div><p className="text-xs font-medium text-slate-400">Step {step} of 3</p></header>
    <div className="h-1 bg-slate-100"><div className="h-full bg-blue-600 transition-all" style={{ width: `${step * 33.333}%` }} /></div>
    <section className="mx-auto flex w-full max-w-2xl flex-1 flex-col justify-center px-6 py-10 sm:px-8">
      {step === 1 && <div><p className="eyebrow">Start with your outcome</p><h1 className="mt-2 text-3xl font-bold tracking-[-.03em] text-slate-950">What should feel easier?</h1><p className="mt-3 text-sm leading-6 text-slate-500">Choose one or more. You can change everything later.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{goals.map(goal => { const Icon = goal.icon; const selected = selectedGoals.includes(goal.id); return <button key={goal.id} onClick={() => toggle(goal.id, selectedGoals, setSelectedGoals)} className={`relative rounded-2xl border p-5 text-left transition ${selected ? "border-blue-500 bg-blue-50/50 ring-4 ring-blue-500/10" : "border-slate-200 hover:border-slate-300"}`}><Icon className={`h-5 w-5 ${selected ? "text-blue-600" : "text-slate-400"}`} /><p className="mt-4 text-sm font-semibold leading-5 text-slate-900">{goal.label}</p>{selected && <span className="absolute right-3 top-3 grid h-5 w-5 place-items-center rounded-full bg-blue-600 text-white"><Check className="h-3 w-3" /></span>}</button>; })}</div></div>}
      {step === 2 && <div><p className="eyebrow">Add useful context</p><h1 className="mt-2 text-3xl font-bold tracking-[-.03em] text-slate-950">Choose your starting tools.</h1><p className="mt-3 text-sm leading-6 text-slate-500">Choose what you want to connect next. Nothing is marked connected until authorization succeeds.</p><div className="mt-8 space-y-3">{tools.map(tool => { const Icon = tool.icon; const selected = selectedTools.includes(tool.id); return <button key={tool.id} onClick={() => toggle(tool.id, selectedTools, setSelectedTools)} className={`flex w-full items-center gap-4 rounded-2xl border p-4 text-left transition ${selected ? "border-blue-500 bg-blue-50/40" : "border-slate-200"}`}><div className="grid h-10 w-10 place-items-center rounded-xl bg-white text-slate-600 shadow-sm"><Icon className="h-[18px] w-[18px]" /></div><div className="flex-1"><p className="text-sm font-semibold text-slate-900">{tool.label}</p><p className="mt-0.5 text-xs text-slate-500">{tool.note}</p></div><span className={`grid h-5 w-5 place-items-center rounded-full border ${selected ? "border-blue-600 bg-blue-600 text-white" : "border-slate-300"}`}>{selected && <Check className="h-3 w-3" />}</span></button>; })}</div></div>}
      {step === 3 && <div className="text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Sparkles className="h-6 w-6" /></div><p className="eyebrow mt-7">Ready when you are</p><h1 className="mt-2 text-3xl font-bold tracking-[-.03em] text-slate-950">Your calmer workspace is ready.</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-500">Continue to Integrations to authorize your tools, then return to the overview.</p><div className="mx-auto mt-8 max-w-md rounded-2xl bg-slate-50 p-5 text-left"><p className="text-xs font-semibold text-slate-700">Included in your setup</p><div className="mt-3 space-y-2 text-xs text-slate-500"><p>• {selectedGoals.length} focus {selectedGoals.length === 1 ? "goal" : "goals"}</p><p>• {selectedTools.length} {selectedTools.length === 1 ? "integration" : "integrations"} ready to connect</p><p>• Tenant-isolated tasks, projects, search, and memory</p></div></div>{error && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-xs text-red-700">{error}</p>}</div>}
    </section>
    <footer className="flex items-center justify-between border-t border-slate-100 px-6 py-5 sm:px-8">{step > 1 ? <button onClick={() => setStep(step - 1)} className="btn-secondary"><ArrowLeft className="h-4 w-4" />Back</button> : <span />}{step < 3 ? <button onClick={() => setStep(step + 1)} disabled={step === 1 && selectedGoals.length === 0} className="btn-primary">Continue<ArrowRight className="h-4 w-4" /></button> : <button onClick={finish} disabled={saving} className="btn-primary">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <>Open workspace<ArrowRight className="h-4 w-4" /></>}</button>}</footer>
  </div></main>;
}
