"use client";

import { FormEvent, useEffect, useState } from "react";
import { Archive, FolderKanban, Loader2, MoreHorizontal, Plus, Trash2 } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { EmptyState } from "@/components/EmptyState";
import { api } from "@/lib/api";

export default function ProjectsPage() {
  const [projects, setProjects] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<any | null>(null);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [status, setStatus] = useState("active"); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { setProjects(await api.getProjects()); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const openCreate = () => { setEditing({ id: null }); setName(""); setDescription(""); setStatus("active"); setError(""); };
  const openEdit = (project: any) => { setEditing(project); setName(project.name); setDescription(project.description || ""); setStatus(project.status); setError(""); };
  const save = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; setSaving(true); setError(""); try { if (editing.id) await api.updateProject(editing.id, { name: name.trim(), description: description.trim() || null, status }); else await api.createProject({ name: name.trim(), description: description.trim() || undefined, color: "blue" }); setEditing(null); await load(); } catch (err: any) { setError(err.message || "Project could not be saved."); } finally { setSaving(false); } };
  const remove = async () => { if (!editing?.id || !window.confirm(`Delete “${editing.name}”? Tasks will remain but will no longer belong to this project.`)) return; setSaving(true); try { await api.deleteProject(editing.id); setEditing(null); await load(); } finally { setSaving(false); } };

  return <AppShell title="Projects" description="Organize outcomes without turning work into another dashboard."><div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Workspaces</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Active projects</h2></div><button onClick={openCreate} className="btn-primary w-fit"><Plus className="h-4 w-4" />New project</button></div>
    {loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#9291A5]" /></div> : projects.length === 0 ? <EmptyState icon={FolderKanban} title="No projects yet" description="Create a lightweight workspace to group related tasks and decisions." action={<button onClick={openCreate} className="btn-primary">Create your first project</button>} /> : <div className="grid gap-4 md:grid-cols-2">{projects.map(project => <article key={project.id} className="surface interactive-card group p-5"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#EEEDFE] text-[#4C3FBF]"><FolderKanban className="h-[18px] w-[18px]" /></div><button onClick={() => openEdit(project)} className="rounded-lg p-2 text-[#9291A5] hover:bg-[#F7F7FC] hover:text-[#1B1B2F]" aria-label={`Edit ${project.name}`}><MoreHorizontal className="h-4 w-4" /></button></div><h3 className="mt-5 text-base font-semibold text-[#1B1B2F]">{project.name}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-[#6B6B80]">{project.description || "A focused workspace for related work."}</p><div className="mt-5 flex items-center justify-between border-t border-[#F0F0F7] pt-4"><span className="text-xs text-[#6B6B80]">{project.open_task_count} open tasks</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold capitalize ${project.status === "active" ? "bg-[#E3FBF7] text-[#00846F]" : "bg-[#F0F0F7] text-[#6B6B80]"}`}>{project.status}</span></div></article>)}</div>}
    {editing && <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/35 p-4 backdrop-blur-sm" onMouseDown={event => event.currentTarget === event.target && setEditing(null)}><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><p className="eyebrow">{editing.id ? "Project settings" : "New workspace"}</p><h3 className="mt-1 text-xl font-bold text-slate-950">{editing.id ? "Edit project" : "Create a project"}</h3><form onSubmit={save} className="mt-6 space-y-4"><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Name</label><input autoFocus className="field" value={name} onChange={event => setName(event.target.value)} placeholder="e.g. Product launch" required /></div><div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Description</label><textarea className="field min-h-24 resize-none" value={description} onChange={event => setDescription(event.target.value)} placeholder="What outcome are you working toward?" /></div>{editing.id && <div><label className="mb-1.5 block text-xs font-semibold text-slate-700">Status</label><select className="field" value={status} onChange={event => setStatus(event.target.value)}><option value="active">Active</option><option value="archived">Archived</option><option value="completed">Completed</option></select></div>}{error && <p className="rounded-xl bg-red-50 px-3 py-2 text-xs text-red-700">{error}</p>}<div className="flex items-center justify-between gap-2 pt-2">{editing.id ? <button type="button" onClick={remove} className="btn-secondary text-red-600" disabled={saving}><Trash2 className="h-4 w-4" />Delete</button> : <span />}<div className="flex gap-2"><button type="button" onClick={() => setEditing(null)} className="btn-secondary">Cancel</button><button className="btn-primary" disabled={saving || !name.trim()}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : editing.id ? <><Archive className="h-4 w-4" />Save</> : "Create project"}</button></div></div></form></div></div>}
  </div></AppShell>;
}
